#!/bin/bash -xv

###############################################################################
export PROJECT_NAME=OpenMAMA-omnm
export PROJECT_VERSION=master
export JIRA_RELEASE=BUS-1781           # release artifact in jira

# internal dependencies
export OPENMAMA_VERSION=master
