#!/bin/bash

# google test
export GOOGLE_TEST="-DGTEST_ROOT="
[[ -n ${GTEST_VERSION} ]] && export GOOGLE_TEST="-DGTEST_ROOT=/build/share/googletest/${GTEST_VERSION}"

OPENMAMA_INSTALL=${INSTALL_BASE}/OpenMAMA/${OPENMAMA_VERSION}/${BUILD_TYPE}
OPENMAMA_SOURCE=${OPENMAMA_INSTALL}/src
LIBZMQ_INSTALL=${INSTALL_BASE}/libzmq/${LIBZMQ_VERSION}/${BUILD_TYPE}
