#!/bin/bash

# google test
[[ -n ${GTEST_VERSION} ]] && export GTEST_ROOT=/build/share/googletest/${GTEST_VERSION}

OPENMAMA_INSTALL=${INSTALL_BASE}/OpenMAMA/${OPENMAMA_VERSION}/${BUILD_TYPE}
OPENMAMA_SOURCE=${OPENMAMA_INSTALL}/src
LIBZMQ_INSTALL=${INSTALL_BASE}/libzmq/${LIBZMQ_VERSION}/${BUILD_TYPE}
LIBEVENT_INSTALL=${INSTALL_BASE}/libevent/${LIBEVENT_VERSION}/${BUILD_TYPE}
